### ISSUE TITLE
PAD token missing ?

### ISSUE THREAD

**Issue by omkar-12bits** [mistralai/mistral-inference#150]
i tried using `eos_token` , `unk_token` and `bos_token` with `left` and `right` padding side but whenever the padding tokens size increases the outputs are pure garbage.

**Comment by omkar-12bits** [comment]
after trying this on both mistral and mixtral its sure that paddings doesn't work very well with these models.
i was just playing with prompts at inference time and saw that paddings makes generation worst.
if inference on batches doesn't work well then how does it performs while training ? shouldn't it also produce garbage ?

**Comment by geronimi73** [comment]
can you post the code you use please?
